runtime: nodejs20
env: standard

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  NODE_ENV: 'production'
